
version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"