name: CI Action
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: CI Run (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }} with composer args "${{ matrix.composer-args }}")
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
        composer-args: ['', '--prefer-lowest']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
      - name: Install Dependencies
        run: |
          composer update --no-progress --no-suggest --prefer-stable --optimize-autoloader ${{ matrix.composer-args }}
      - name: Static Analysis
        run: composer phpstan
      - name: Code Style Check
        run: composer style-check
      - name: Test
        run: composer test-with-coverage
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) -f ./clover.xml
